baseurl = "https://gxfreee.com/"
title = "Gxfreee.com"
languageCode = "en-us"
paginate = "5" # Number of posts per page
theme = "mainroad"
disqusShortname = "" # Enable comments by entering your Disqus shortname
googleAnalytics = "" # Enable Google Analytics by entering your tracking id

[Author]
  name = "Mohan❤️R"
  bio = "Mohan❤️R is a passionate tech enthusiast and a dedicated developer. With a keen eye for emerging trends and a knack for problem-solving, he immerses himself in the world of technology and development. Mohan❤️R's love for coding and all things tech-driven has fueled his journey to become a trusted resource in the industry"
  avatar = "img/avatar.png"

[Params]
  description = "Unlock Your Tech Potential at GXFreee.com: Insights, Tutorials, and Industry Trends for Developers. Join our vibrant community for growth and innovation!" # Description of your site 
  opengraph = true
  twitter_cards = false
  readmore = true # Show "Read more" button in list if true
  authorbox = true
  pager = true
  post_meta = ["date", "categories"] # Order of post meta information
  mainSections = ["post", "docs"]
  toc = true # Enable Table of Contents

[Params.logo]
  subtitle = "Coding. Creativity. Success 🙂" # Logo subtitle

[Params.sidebar]
  home = "right"   # Configure layout for home page
  list = "right"   # Configure layout for list pages
  single = "right" # Configure layout for single pages
  # Enable widgets in given order
  widgets = ["search", "recent", "categories", "taglist"]

[Params.widgets]
  recent_num = 5 # Set the number of articles in the "Recent articles" widget
  tags_counter = false # Enable counter for each tag in "Tags" widget (disabled by default)

[Params.widgets.search]
  cached = false # activate cache if true
  url = "/search/"
[Params.widgets.search.input]
  name = false
  pre = ""


[Params.style.vars]
  highlightColor = "#3d89c9"

[sitemap]
  changefreq = "daily"
  filename = "sitemap.xml"
  priority = 1


[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

enableRobotsTXT = true
canonifyURLs = true
# and if you think your md file names or locations might change:
[permalinks]
    post = "/blog/:title/"